spring:
  application:
    name: gateway-proxy-demo
  cloud:
    gateway:
      routes:
        - id: proxy_route
          uri: http://localhost:9000
          predicates:
            - Path=/proxy/**
          filters:
            - RewritePath=/proxy/(?<segment>.*), /${segment}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB